### ISSUE TITLE
Expose validate()

### ISSUE THREAD

**Issue by wolfgangwalther** [supabase/pg_jsonschema#14]
Currently, only is_valid() is exposed, which just returns a bool.

It would be great to expose validate(), too, to get actual validation errors thrown (with information about **why** the validation is failing...).

**Comment by duguorong009** [comment]
@wolfgangwalther @olirice 
I would like to contribute to the project, and take this issue.
Can you take a look at PR #32 ?

**Comment by zakandrewking** [comment]
I wonder if this would make it possible to return meaningful validation errors for CHECK constraints. For now, all we get for an invalid insert is:

```
ERROR:  new row for relation "node" violates check constraint "node_column_check"
```
