### ISSUE TITLE
Provide instructions for installing pg_jsonschema in Dockerfile

### ISSUE THREAD

**Issue by gajus** [supabase/pg_jsonschema#25]
I've tried:

```Dockerfile
RUN apt install -y curl cmake pkg-config libssl-dev clang postgresql-server-dev-15
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
RUN cargo install cargo-pgx && cargo pgx init --pg15 /usr/bin/pg_config

RUN \
  mkdir pg_jsonschema && \
  cd pg_jsonschema && \
  curl -L 'https://github.com/supabase/pg_jsonschema/archive/refs/tags/v0.1.4.tar.gz' | tar -xz --strip-components=1 && \
  cargo pgx install
```

but this gives an error:

>  `pgx-0.6.0-alpha.1` shouldn't be used with `cargo-pgx-0.7.4`, please use `pgx = "~0.7.4"` in your `Cargo.toml`

It seems like `pg_jsonschema` is expecting a very specific version of pgx?

I was able to workaround it with:

```Dockerfile
RUN cd pg_jsonschema && sed -i 's/"=0.6.0-alpha.1"/"~0.7.4"/g' Cargo.toml && cargo pgx install
```

**Comment by olirice** [comment]
Did you see https://github.com/supabase/pg_jsonschema/blob/master/dockerfiles/db/Dockerfile ?

**Comment by gajus** [comment]
I did. It didn't quite explain to me the pgx version mismatch. Admittedly, I am not familiar with Rust ecosystem, so might be overlooking something obvious.

**Comment by olirice** [comment]
I'm not sure why you're running into that problem but 
```
cargo install cargo-pgx --version 0.7.1 --locked
```
is the relevant line

you'll want to match it to what's in the `Cargo.toml` file

**Comment by gajus** [comment]
I think I am missing something obvious, but how would I install multiple extensions using pgx if they all require different pgx versions? For what it is worth, the patch that I've shared works. So it seems like it is `pg_jsonschema` that should relax its dependencies.

**Comment by olirice** [comment]
bad news! you have to set up the specific required toolchain before installing each extension. If they require two different versions of cargo-pgx, you'd have to uninstall the wrong version and re-install the correct version.

Thats one of the reasons we have build artifacts for common systems in the [releases](https://github.com/supabase/pg_jsonschema/releases/tag/v0.1.4), so users can:

```shell
wget -L https://github.com/supabase/pg_jsonschema/releases/download/v0.1.4/pg_jsonschema-v0.1.4-pg15-amd64-linux-gnu.deb
dpkg -i pg_jsonschema-v0.1.4-pg15-amd64-linux-gnu.deb
```

which is another option you could use inside docker if you'd prefer not to install from source

**Comment by gajus** [comment]
> bad news! you have to set up the specific required toolchain before installing each extension. If they require two different versions of cargo-pgx, you'd have to uninstall the wrong version and re-install the correct version.

but why not just relax pgx version constraints?

**Comment by olirice** [comment]
> why not just relax pgx version constraints?

pgx is evolving quickly. We've had 2 instances where patch version upgrades in pgx have caused one of our extensions to fail to compile. Following that experience we pin exact versions to avoid risking CI failures outside of our control (when new versions of pgx release)
