### ISSUE TITLE
prx renamed to pgrx and installation now fails

### ISSUE THREAD

**Issue by adam-expa** [supabase/pg_jsonschema#26]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

`pgx` has renamed to `pgrx` which now has a different installation folder (https://github.com/tcdi/pgrx). This causes the installation to fail when run with `cargo pgrx run` as the installer is looking for the config in the `.pgx/` folder and `pgrx` places it in `.pgrx/`. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Install `pgrx` https://github.com/tcdi/pgrx
2. Cone this repo
3. Run `cargo pgrx run`
4. See error: `Error: /Users/USER/.pgx/config.toml not found.  Have you run `cargo pgx init` yet?`

## Expected behavior

I expected to be able to install the plugin

## Screenshots

N/A

## System information

- OS:macOS

**Comment by imor** [comment]
I just tested with the latest on Ubuntu and I was able to run with `cargo pgrx run`. Maybe this has been fixed by some recent commit?

**Comment by olirice** [comment]
@adam-expa that error is related to pgrx generally

pgrx creates and manages its own versions of postgres so you can quickly test/run against 11-15 and you have to initialize it before interacting with any pgrx projects

Take a look at the pgrx docs here https://github.com/tcdi/pgrx#getting-started

and the docker compose file for minimal repro setup
https://github.com/supabase/pg_jsonschema/blob/master/dockerfiles/db/Dockerfile

I'm going to close this for now but please follow up if you have any trouble
