### ISSUE TITLE
Validating the schemae themselves

### ISSUE THREAD

**Issue by deleted** [supabase/pg_jsonschema#28]
If you are storing user-submitted JSONSchema in the database to do JSON validation dynamically, it's nice to be able to ensure that the schemae themselves are in fact valid JSONSchema.

I think this could be pretty easily implemented in the extension by calling into `jsonschema::compile()`.

Maintainers, is this a feature-add you'd consider accepting and if so, any opinions on function naming or signature?
`fn json_schema_is_valid(schema: Json) -> bool` would be my first suggestion.

**Comment by olirice** [comment]
There's definitely value in it, but defining the schema is fairly infrequent and there are existing tools that provide a much better DX than we'll be able to do in the database like https://www.jsonschemavalidator.net

For that reason, I'd prefer to keep `pg_jsonschema` constrained to the minimum set of functions required to operate in production

**Comment by deleted** [comment]
That tool only works if my users bother to use it.

Without being able to check at admission time whether user-submitted schemae are valid JSONSchema, we have to wait until users insert data against them to find out. So for my usecase, I'd consider this function required for production.

To be clear: I'm pretty sure I need this feature, so I'm offering to implement it, if you're open to that.
