### ISSUE TITLE
Do tests make sense?

### ISSUE THREAD

**Issue by apeschar** [supabase/pg_jsonschema#3]
I saw this on Hacker News, and didn't run it or anything, but from first glance the test cases don't make sense.

* All test cases end with `assert_eq!(result, false);`, even those that are supposed to test a matching schema.
* The `test_jsonb_*` tests don't test the `jsonb_matches_schema` function, but are identical to the `json` tests.

https://github.com/supabase/pg_jsonschema/blob/fb7ab09bf6050130e8d656f2999ec0f6a3fedc0d/src/lib.rs#L57-L99

**Comment by olirice** [comment]
> Do tests make sense?

they did not :)

**Comment by apeschar** [comment]
The second point still stands: the test cases named `jsonb` are not testing the `jsonb` functions; they are identical to the `json` tests.
