### ISSUE TITLE
how to use jsonschema_is_valid and jsonschema_validation_errors

### ISSUE THREAD

**Issue by MohammedFaragallah** [supabase/pg_jsonschema#37]
after running 

```SQL
create extension pg_jsonschema;
```

I only get `json_matches_schema` and `jsonb_matches_schema` how to use the others with superbase

**Comment by olirice** [comment]
the deployed version of pg_jsonschema on supabaes is `0.1.4` you can check that on your instance with 
```sql
select * from pg_available_extensions where name = 'pg_jsonschema'
```
we're expecting to create a new release and enable it on new projects NLT next week in prep for launching pg16
