### ISSUE TITLE
Error message too unspecific

### ISSUE THREAD

**Issue by egze** [supabase/pg_jsonschema#55]
# Bug report

The validation error messages are too unspecific. It would help to know the path to the field that has errors.

## Describe the bug

Example query
```SQL
SELECT jsonschema_validation_errors(
            '{
                "type": "object",
                "properties": {
                    "tags": {
                        "type": "array",
                        "items": {
                            "type": "string",
                            "maxLength": 16
                        }
                    }
                }
            }'::json,
            '{"tags": [1,2,3]}'
        )
```
produces the error message
```
{"1 is not of type \"string\"","2 is not of type \"string\"","3 is not of type \"string\""}
```

It would be great to see a json-path to the field. Something like so:
```
{
  "$.tags[0]": "1 is not of type \"string\",
  "$.tags[1]": "2 is not of type \"string\",
  "$.tags[2]": "3 is not of type \"string\",
}
```

Otherwise the error message if not actionable.

**Comment by olirice** [comment]
pg_jsonschema is a very [light weight](https://github.com/supabase/pg_jsonschema/blob/29fcd5b23abe3dd6a78a490082f34113de7813a1/src/lib.rs#L5-L43) wrapper around [jsonschema-rs](https://github.com/Stranger6667/jsonschema-rs). This project bubbles up error messages from that underlying library so I'd recommend opening this on the [jsonschema-rs issue tracker](https://github.com/Stranger6667/jsonschema-rs/issues/new) if you have thoughts on how he error messages could be improved
