### ISSUE TITLE
Failed Release: Missing PGXN Credentials

### ISSUE THREAD

**Issue by theory** [supabase/pg_jsonschema#65]
Follow-up to #54.

[This failure](https://github.com/supabase/pg_jsonschema/actions/runs/11368783793/job/31624678827) suggests that the necessary PGXN credentials have not been added as `PGXN_USERNAME` and `PGXN_PASSWORD` workflow secrets to this repository (or your or settings to apply to all your extensions that use a workflow like this). If you haven't created a PGXN account yet, [request one](https://manager.pgxn.org/account/register) and I will approve ASAP.

**Comment by olirice** [comment]
thanks, requested

**Comment by theory** [comment]
Approved!

**Comment by olirice** [comment]
ty, should be resolved for the next release
